import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React from "react";
import Footer from "../../components/Footer";
import Nav from "../../components/Nav";
import styles from "../../styles/Home.module.css";
import { paramSingle } from "../utils/urlHelper";
import { getArticles } from "./data";

const Articles: NextPage = () => {
  const router = useRouter();
  const { name } = router.query;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App - Articles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Nav />
        <h1 className={styles.title}>Articles</h1>
        <ul>
          {getArticles({ name: paramSingle(name) }).map(({ name, id }) => (
            <Link key={id} href={`/articles/${id}`}>
              <a>
                <li>{name}</li>
              </a>
            </Link>
          ))}
        </ul>
      </main>

      <Footer />
    </div>
  );
};

export default Articles;
