import { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import Footer from "../../components/Footer";
import styles from "../../styles/Home.module.css";
import { paramSingle } from "../utils/url_helper";
import { getArticles } from "./data";

const Articles: NextPage = () => {
  const router = useRouter();
  const { name } = router.query;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App - Articles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Articles</h1>
        {getArticles({ name: paramSingle(name) }).map(({ name, id }) => (
          <h2 key={id}>{name}</h2>
        ))}
      </main>

      <Footer />
    </div>
  );
};

export default Articles;
