import { NextPage } from "next";
import Head from "next/head";
import React from "react";
import DictionarySearch from "../../components/DictionarySearch";
import Footer from "../../components/Footer";
import Nav from "../../components/Nav";
import styles from "../../styles/Home.module.css";

const Dictionary: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App - Dictionary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Nav />
        <h1 className={styles.title}>Dictionary</h1>
        <DictionarySearch />
      </main>

      <Footer />
    </div>
  );
};

export default Dictionary;
