import { NextPage } from "next";
import Head from "next/head";
import React from "react";
import Footer from "../components/Footer";
import Nav from "../components/Nav";
import styles from "../styles/Home.module.css";

const About: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App - About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Nav />
        <h1 className={styles.title}>About</h1>
      </main>

      <Footer />
    </div>
  );
};

export default About;
